# -*- coding: utf-8 -*-
"""da1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3-CJK1XP_7lCHehXhWsOZbd4fkSH3HY
"""

a=20
b=30

a

b

a_=6

a_

a=6.2+3J

type(a)

name="srinu"

type('name')

name

name[0:2]

name[1:3]

name[-1]

name[-2]

name[-1:-3]

name1="srinu"
name2="chaitu"
name3="yugi"

name1.upper()

name1.lower()

print(name1)
name1.isupper()

name1="data seIEnce"
name1.title()

name1="srinu"
name1.capitalize()

name1="sRinU"
name1.swapcase()

name1="srinu reddy"
name1.isalpha()

name1="srinureddy"
name1.isalpha()

string="sri1234"
string.isalnum()

string="123456"
string.isalnum()

string="srinu reddy"
string.startswith('srinu')

name="    "
name.isspace()































