# -*- coding: utf-8 -*-
"""day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zx39mGneefG8yothpN2e1Sv9AAfpzO76
"""

x="data"
len(x)

name="srinu reddy"
name.find("i")

name="srinu reddy"
name.find("ynct")

name=" srinu "
len(name)

name.strip()

name="  srinu  "
name.lstrip()

name="  srinu  "
name.rstrip()

x="stinu"

x.replace("t","r")

x="srinu"
x.center(7,"@")

x="60"

x.zfill(7)

x.zfill(21)

x='''srinu
reddy'''

x.split()



















