# -*- coding: utf-8 -*-
"""day3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXTyHI_v3aplI14p09KsuDv1-R15qMQn
"""

x=[1,2,3,4,5,6,[7,8,9,]]
len(x)

type(x)

x=[1,2,3,4]
y=[3,4,5,]
x.append(y)
len(x)

x=[1,2,3,4]
y=[5,6,7,8]
x.extend(y)
len(x)

x

x=[1,1,2,3,4,5,6,1,1]
x.count(1)

x=[1,2,3,4,5]
y=x[2:4].copy()
print(y)
y[1]=222
print(y)
print(x)

x=[1,2,3,4,5]
y=x[2:4].deepcopy()
print(y)
y[0]=666
print(y)
print(x)

x=[1,2,3,5,7]
y=x
y[0]=333
print(x)
print(y)

x=[1,2,3,4,5]
y=x.copy()
y[0]=666
print(x)
print(y)

x=[1,2,3,6,5,7]
x.clear()
x

x=[1,2,3,4,5,6,7]
x.remove(3)
x

x=[1,2,3,4,5,6]
x.pop(3)
x

x=[1,2,3,4,5,'srinu']
x.reverse()
x

x=[5,6,5,4,4,3]
x.sort()
x

x={1,2,3,4,5,6,7}
type(x)

x=[1,2,3,4]
x[1]=666
x



x={1,2,3,4,5,6,7,8,9}
y={4,5,6,7,8}
x.union(y)

x={1,2,3,4,5,6,7}
y={5,6,7}
x.intersection(y)

x={1,2,3,5,6,7,8}
y={3,4,5,6,7,9}
x.difference(y)

x={1,2,5,6,7}
y={2,5,6}
print(x.issubset(y))
print(y.issubset(x))
print(x.issuperset(y))
print(x.isdisjoint(y))

x={1,2,3,4,5,6,7}
y={4,5,6,7}
x.symmetric_difference(y)

x={1,2,3,5,7,8}
y={3,4,5,7}
x.symmetric_difference_update(y)
print(x)
print(y)









