# -*- coding: utf-8 -*-
"""Yet another copy of day4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPNMYikVGFkmX8V9zQOubv3g-hvOU7th
"""

d={"key":10,}
type(d)

d

my_dict = {
    "name": "srinu",
    "age": 21,
    "location": "singavaram"
}

my_dict["name"]

my_dict

mixed_dict = {
    "name": "srinu",
    666: [45,87,89],
    2.14: {"unit": "pi"},
    True: "Active"}

mixed_dict

mixed_dict[666][-1]



employee = {
    "id": 666,
    "name": "srinu reddy",
    "department": {
        "name": "Data Science",
        "location": "bangalore",
        "floor": 6
    },
    "is_active": True
}

employee["name"]

employee['department']['location']

temp={
   "lat":33.44,
   "lon":-94.04,
   "timezone":"America/Chicago",
   "timezone_offset":-18000,
   "current":{
      "dt":1684929490,
      "sunrise":1684926645,
      "sunset":1684977332,
      "temp":292.55,
      "feels_like":292.87,
      "pressure":1014,
      "humidity":89,
      "dew_point":290.69,
      "uvi":0.16,
      "clouds":53,
      "visibility":10000,
      "wind_speed":3.13,
      "wind_deg":93,
      "wind_gust":6.71,
      "weather":[
         {
            "id":803,
            "main":"Clouds",
            "description":"broken clouds",
            "icon":"04d"
         }
      ]
   } }

temp

temp['timezone']

temp['current']['temp']

d = {
    "name": "srinu",
    "age": 21,
    "location": "singavaram"
}

d.values()

d['name']

temp.values()

temp.keys()

temp.items()

d

d.get('age')

d['name']

d.clear()

d = {
    "name": "srinu",
    "age": "21",
    "location": "bangalore"
}

d

d.popitem(1)

d

isinstance(d,dict)

isinstance(d['age'],int)

























